import random


def question_options(options: list) -> str:
    """
    Return a random question string from the list available.
    This chooses a random start and end phrase to create a large number of unique question formulations.
    """

    end_phrase = [
        "Discuss it with your quiz team and give me your best guess.",
        "Discuss it with your quiz team and give me the country you think it is.",
        "Let's hear your team's prediction on which country it might be.",
        "After some deliberation, I want to know your team's estimation of the country.",
        "It's time to huddle up and come up with your most informed guess on the country.",
        "Talk amongst yourselves and then share your team's country selection.",
        "Collaborate and give me the name of the country that you think it is.",
        "After some discussion, I want to hear your team's best guess on the country.",
        "Take a few moments to confer with your team and offer the name of the country you think it is.",
        "Let's hear your team's most confident country guess after some collaboration.",
        "It's time to put your heads together and come up with a country name that you think fits.",
        "Work together to come up with your team's most informed country selection.",
        "After some deliberation, I want to hear your team's most accurate country guess.",
        "Take a moment to discuss with your team and share the country you think it is.",
        "It's time to collaborate and give me your team's best guess on the country.",
        "Discuss it with your quiz team and offer the name of the country you think it is.",
        "Let's hear your team's most educated guess on the country after some deliberation.",
        "After some discussion, I want to know your team's most confident country estimation.",
        "Take a few moments to confer with your team and offer your most accurate country guess.",
        "It's time to put your heads together and come up with your most informed country selection.",
        "Work together to give me the name of the country that you think it is.",
        "After some deliberation, I want to hear your team's best country guess.",
        "Collaborate and give me the country name that you think it is.",
        "Discuss it with your quiz team and share your most well-reasoned country selection.",
        "Let's hear your team's most calculated guess on the country after some collaboration.",
        "After some discussion, I want to know your team's most thoughtful country estimation.",
        "It's time to huddle up and come up with your most confident guess on the country.",
        "Take a few moments to confer with your team and offer your most well-informed country guess.",
        "Work together and give me the name of the country that you think it is.",
        "After some deliberation, I want to hear your team's most accurate estimation of the country.",
        "Collaborate and give me your team's most informed country guess.",
        "Discuss it with your quiz team and give me your most educated country selection.",
        "Let's hear your team's most calculated country guess after some collaboration.",
        "After some discussion, I want to know your team's most thoughtful country estimation.",
        "It's time to put your heads together and come up with your most confident country selection.",
        "Work together and give me the name of the country that you think it is.",
        "After some deliberation, I want to hear your team's most well-reasoned country guess.",
        "Collaborate and offer your team's most thoughtful country selection.",
        "Discuss it with your quiz team and give me your most informed guess on the country.",
        "Let's hear your team's most accurate country selection after some collaboration.",
        "After some discussion, I want to know your team's most confident estimation of the country.",
        "It's time to put your heads together and come up with a well-informed guess.",
        "I want to hear your team's guess after some discussion and collaboration.",
        "Take a moment to discuss with your team before offering your most thoughtful guess.",
        "Let's hear your team's prediction after a little bit of brainstorming.",
        "Work together to come up with your best guess and share it with me.",
        "I want to hear your team's most calculated guess after some discussion.",
        "It's time to collaborate and come to a consensus before making your guess.",
        "Take a few moments to discuss with your team before offering your most confident guess.",
        "It's time to combine your knowledge and make your best collective guess.",
        "After some deliberation, I want to hear your team's most informed guess.",
        "Work together to make your most accurate guess and share it with me.",
        "Let's hear your team's most well-reasoned guess after some collaboration.",
        "I want to know your team's prediction after a little bit of group discussion.",
        "It's time to put your heads together and come up with a thoughtful guess.",
        "After some deliberation, I want to hear your team's most calculated guess.",
        "Take a few moments to confer with your team and offer your most confident guess.",
        "It's time to collaborate and come up with a well-informed guess.",
        "Now is the time to work together and make your best guess.",
        "Talk amongst yourselves and then share your team's most educated guess.",
        "After a little bit of brainstorming, I want to hear your team's prediction.",
        "It's time to combine your knowledge and make your best collective guess.",
    ]
    
    middle = f"Is this the flag of {options[0]}, {options[1]}, {options[2]} or {options[3]}?"

    questions = [
        f"Which country's flag is about to be displayed?",
        f"Can you identify the upcoming flag?",
        f"What is the flag that will be shown next?",
        f"Do you recognize the flag that is about to be revealed?",
        f"Which nation's banner will be shown next?",
        f"What's the next country flag that will be displayed?",
        f"Which national flag is coming up next?",
        f"Which flag is about to be unveiled?",
        f"Can you predict the next flag to be shown?",
        f"Which flag is scheduled to be displayed next?",
        f"What flag is next in line to be shown?",
        f"Do you know the flag that will be displayed next?",
        f"Which nation's banner will be displayed next?",
        f"What country's flag will be shown next?",
        f"Which flag will be raised next?",
        f"What is the upcoming flag?",
        f"Can you identify the flag that will be displayed next?",
        f"What is the next country's flag to be shown?",
        f"Which flag will be on display next?",
        f"What is the next flag in the queue?",
        f"What flag is next to be raised?",
        f"Which flag is next in the sequence?",
        f"What flag is coming up next in the lineup?",
        f"Which flag is next on the list?",
        f"What flag will be raised next?",
        f"What is the flag that will be shown immediately after this?",
        f"Which country's flag is next on the list?",
        f"Which flag will be unveiled after this one?",
        f"Can you guess the next flag that will be shown?",
        f"Which flag will be up next?",
        f"What flag will be displayed next in the lineup?",
        f"Which country's banner is up next?",
        f"Which flag is the next to be revealed?",
        f"What flag will be shown after this one?",
        f"What is the flag that will be displayed immediately following this?",
        f"Which country's flag comes after this one?",
        f"What is the next flag that will be raised up?",
        f"Which flag will be displayed after this one is taken down?",
        f"What is the upcoming flag to be displayed?",
        f"Can you identify the flag that will be shown after this?",
        f"Which flag will be up right after this one?",
        f"Which flag is next in the order?",
        f"What is the next national flag to be displayed?",
        f"What is the next flag that will be unveiled?",
        f"Which country's banner will be raised next?",
        f"What is the flag that is coming up next?",
        f"Can you guess the flag that will be displayed immediately after this one?",
        f"Which flag is next in the lineup?",
        f"What is the next flag that will be raised up?",
        f"Which national flag is scheduled to be shown next?",
    ]

    return f"{questions[random.randint(0, len(questions)-1)]} {middle} {end_phrase[random.randint(0,len(end_phrase) -1)]}"


def greeting_options():
    """Provide some randomisation of the greeting at the start of the quiz."""
    greetings = [
        "Up for a team challenge? Let's see if you can match each flag to its country!",
        "Fancy a cooperative game? Put your knowledge to the test by associating each flag with its country!",
        "Care to join in? Match the flag with its respective country and let's see how you do!",
        "Are you game for a game? Show us your skills by matching the flag to its country.",
        "Feeling up for a group game? See if you can identify the country by the flag!",
        "Care to take a shot? Try to connect each flag with the right nation!",
        "Shall we give it a go? Pick which country each flag represents!",
        "Up for a game? See if you can match the flag to the country it belongs to!",
        "Shall we start? See if your knowledge is up to par by matching each flag to its home nation!",
        "Do you think you can do it? Connect the flag with the correct country!",
        "Ready to play? Let's test your knowledge by matching the flag to the nation!",
        "Want to give it a shot? Link each flag with its corresponding country!",
        "Would you like to take a chance? Can you identify the country by the flag?",
        "Would you be daring enough to try? Uncover the nation hidden behind the flag!",
        "Are you ready? See if you can recognize the country from the flag!",
        "Are you game? See if you can identify the flag's country of origin!",
        "Would you like to play? Match the flag with the corresponding country to complete the puzzle!",
        "Up for a challenge? Try to recognize each flag's country!",
        "Would you like to try a game? See if you figure out the country of each flag.",
        "Are you ready? See if you can connect the flag to its home nation!",
    ]
    return greetings[random.randint(0, len(greetings)-1)]

